### ISSUE TITLE
Optimize `AtomicU128::{load, store}`

### ISSUE THREAD

**Issue by ibraheemdev** [taiki-e/portable-atomic#10]
> Processors that enumerate support for Intel® AVX (by setting the feature flag CPUID.01H:ECX.AVX[bit 28]) guarantee that the 16-byte memory operations performed by the following instructions will always be carried out atomically:
> - MOVAPD, MOVAPS, and MOVDQA.
> - VMOVAPD, VMOVAPS, and VMOVDQA when encoded with VEX.128.
> - VMOVAPD, VMOVAPS, VMOVDQA32, and VMOVDQA64 when encoded with EVEX.128 and k0 (masking disabled).
> 
> (Note that these instructions require the linear addresses of their memory operands to be 16-byte aligned.)

`AtomicU128::{load, store}` can take advantage of this instead of using the more expensive cmpxchg instruction. See this GCC issue/patch for details: https://gcc.gnu.org/bugzilla//show_bug.cgi?id=104688.

**Comment by ibraheemdev** [comment]
As of ARM v8.4 the LDP/STP instructions are guaranteed to be single-copy atomic for 16 byte accesses:

> Changes to single-copy atomicity in Armv8.4 In addition to the single-copy atomicity requirements listed above:

> Instructions that are introduced in FEAT_LRCPC are single-copy atomic when all of the following conditions are true:
> - All bytes being accessed are within the same 16-byte quantity aligned to 16 bytes.
> - Accesses are to Inner Write-Back, Outer Write-Back Normal cacheable memory.

> If FEAT_LSE2 is implemented, all loads and stores are single-copy atomic when all of the following conditions are true:
> - Accesses are unaligned to their data size but all bytes being accessed are within a 16-byte quantity that is aligned to 16 bytes.
> - Accesses are to Inner Write-Back, Outer Write-Back Normal cacheable memory.

> If FEAT_LSE2 is implemented, LDP, LDNP, and STP instructions that load or store two 64-bit registers are single-copy atomic when all of the following conditions are true:
> - The overall memory access is aligned to 16 bytes. > - Accesses are to Inner Write-Back, Outer Write-Back Normal cacheable memory.

**Comment by taiki-e** [comment]
Btw, recently I learned that powerpc64 (pwr8+) supports 128-bit atomics ([llvm patch](https://reviews.llvm.org/D122377). although [qemu doesn't seem to support some of them](https://github.com/taiki-e/atomic-maybe-uninit/blob/4346eb7349fa91fdc6e8b1bba1f6c2a7a3d3174f/src/arch/powerpc.rs#L421)) and [added support for it to another library](https://github.com/taiki-e/atomic-maybe-uninit/blob/4346eb7349fa91fdc6e8b1bba1f6c2a7a3d3174f/src/arch/powerpc.rs#L218-L369). I plan to do the same with this library.

**Comment by taiki-e** [comment]
Once #16 merged, the list of targets that support 128-bit atomics and the instructions used is as follows.

| target_arch | load | store | CAS | note |
| ----------- | ----- | ----- | ---- | ---- |
| x86_64 | cmpxchg16b or vmovdqa | cmpxchg16b or vmovdqa | cmpxchg16b | cmpxchg16b target feature required. vmovdqa requires Intel CPU with AVX. <br> Both compile-time and run-time detection are supported for cmpxchg16b. vmovdqa is currently run-time detection only.  <br> Requires rustc 1.59+ when cmpxchg16b target feature is enabled at compile-time, otherwise requires nightly | 
| aarch64 | ldxp/stxp or ldp | ldxp/stxp or stp | ldxp/stxp or casp | casp requires lse target feature, ldp/stp requires lse2 target feature. <br> Both compile-time and run-time detection are supported for lse. lse2 is currently compile-time detection only.  <br> Requires rustc 1.59+ |
| powerpc64 | lq | stq | lqarx/stqcx. | Little endian or target CPU pwr8+. <br> Requires nightly | 
| s390x | lpq | stpq | cdsg | Requires nightly |

Note: Run-time detections require outline-atomics optional feature of this crate

**Comment by taiki-e** [comment]
Other optimizations:

- #20
- #21
- #22


(Apart from these, there have also been some minor optimizations regarding inline assembly since #16 was merged.)

**Comment by taiki-e** [comment]
AMD now guarantees atomicity of 128-bit sse: https://gcc.gnu.org/bugzilla//show_bug.cgi?id=104688#c10

> Apologies for late response!
> 
> We would update the AMD APM manuals in the next revision.
> 
> For all AMD architectures,
> 
> Processors that support AVX extend the atomicity for cacheable, naturally-aligned single loads or stores from a quadword to a double quadword.
> 
> which means all 128b instructions, even the *MOVDQU instructions, are atomic if they end up being naturally aligned.
> 
> Can we extend this patch to AMD processors as well. If not, I will plan to submit the patch for stage-1!
