### ISSUE TITLE
defmt for portable-atomic ?

### ISSUE THREAD

**Issue by gobftald** [taiki-e/portable-atomic#147]
atomic 'load' and 'store' operations' 'asserts_xxx_ordering' calls contain 'panics' and there is even a Debug formatted 'enum Ordering' in 'unreachable!("{:?}", order)'
these codes add  about 250 bytes of memory to every  'load' and 'store' which could be saved by introducing optional/featured defmt  at that points

**Comment by taiki-e** [comment]
Hmm. I thought the compiler could remove `unreachable!("{:?}", order)` because they are literally never reachable (since they are only for handling non_exhaustive). If the compiler can't handle things well there, the correct solution would be to simply remove `"{:?}", order`.

Is this report based on actual project measurements? Or is it theoretical? Usually assertions about order can be optimized and removed by inlining, but is that not working well?

**Comment by gobftald** [comment]
You are right, and there is no problem with this in "release" mode. But unfortunately I have to compress my code even in 'debug' mode. But I admit that this is not a mass need. I will make a custom version of the relevant part of your code for this purposes.

**Comment by taiki-e** [comment]
Removed `"{:?}", order` from `unreachable` in [be3e185](https://github.com/taiki-e/portable-atomic/commit/be3e1854c6eab2fdadc0294afecd2195473674e9).

If we want to reduce the size in debug mode, it depends on the profile, but I believe there are ways to reduce more.

Could you tell me more about your concrete use case? Ideally, I would be able to confirm how effective the patch is...

**Comment by gobftald** [comment]
thank you for your kind and quick responses
