### ISSUE TITLE
New Version of portable-atomic-util

### ISSUE THREAD

**Issue by BjornTheProgrammer** [taiki-e/portable-atomic#158]
Hello, 

I'm just wondering when a new version of `portable-atomic` and `portable-atomic-util` will be published to crates.io. I'm currently trying to make [ndarray](https://github.com/rust-ndarray/ndarray/pull/1384) compatible with different architectures, and only by linking to the git repo does this work. Of course, there's no rush if you have some other blockers. Thank you for the extensive work that you have done with these crates.

**Comment by taiki-e** [comment]
Since no new APIs have been added to `portable-atomic` since the last release, it appears that the only thing that actually needs a new release in your use case is `portable-atomic-util`.

And, `portable-atomic-util`'s release blocker (documentation) has just been resolved, so I will release a new version of `portable-atomic-util` today or tomorrow.

**Comment by taiki-e** [comment]
Published portable-atomic-util 0.2.0.
